autofill:
  BLE_ID: ABCDEFGHIJ
  MKEY: YmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmI=
  PATIENT_BLE_PWD: ABCDEFGHIJ
  PKEY: 2FDIU7I6KPZX4H9QOS6EQLDJGHD2UT5HX0E8BEKM0BKWIAX3DT
  govId: ''
  patientName: Test
  sn: '259710800'
certificates:
  combined_name: combined.pem
  iot_cert_name: IoTCore_certificate_final.pem.crt
  private_key_name: private_final.pem.key
logging:
  enable_debug: true
  log_file: ./fpd_debug.log
  log_to_file: true
paths:
  certs: ./certs
  output_root: C:/Users/eldarb2/Downloads
  temp: ./temp
qr:
  davinci_cloud_url: a1ngo0wsq2lw86-ats.iot.eu-central-1.amazonaws.com
  mqtt_prefix_davinci: davinci/dev/things
  mqtt_prefix_newton: newton/dev/things
  newton_cloud_url: a1y5k9515f72z8-ats.iot.eu-central-1.amazonaws.com
sap:
  base_url: https://tlvm7aappd040.cfrf.medtronic.com/sap/bc
  cert_endpoint: zws_g_get_sn
  client: '300'
  key_endpoint: zws_g_get_keys
ui:
  default_height: 900
  default_width: 1180
  font: Segoe UI
  theme: dark
  version: v4.2.5
